# Generated by Django 5.1.7 on 2025-03-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='genre',
            new_name='category',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='Sem descrição disponível.'),
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
    ]
